from config.constants.feishu import (
    ALERTPUSH_APP_ID_ENV,
    ALERTPUSH_APP_SECRET_ENV,
    FEISHU_ALARM_RECEIVE_ID_ENV,
    FEISHU_ALARM_RECEIVE_ID_TYPE_ENV,
    FEISHU_APP_ID_ENV,
    FEISHU_APP_SECRET_ENV,
)


def test_feishu_env_names():
    assert FEISHU_APP_ID_ENV == "FEISHU_APP_ID"
    assert FEISHU_APP_SECRET_ENV == "FEISHU_APP_SECRET"
    assert ALERTPUSH_APP_ID_ENV == "ALERTPUSH_APP_ID"
    assert ALERTPUSH_APP_SECRET_ENV == "ALERTPUSH_APP_SECRET"
    assert FEISHU_ALARM_RECEIVE_ID_ENV == "FEISHU_ALARM_RECEIVE_ID"
    assert FEISHU_ALARM_RECEIVE_ID_TYPE_ENV == "FEISHU_ALARM_RECEIVE_ID_TYPE"
