"""Feishu integration env-var names.

Chat transport uses the interactive app (FEISHU_*); alarm delivery uses the
dedicated alert-push app (ALERTPUSH_*) plus the receive-id target.
"""

FEISHU_APP_ID_ENV = "FEISHU_APP_ID"
FEISHU_APP_SECRET_ENV = "FEISHU_APP_SECRET"
ALERTPUSH_APP_ID_ENV = "ALERTPUSH_APP_ID"
ALERTPUSH_APP_SECRET_ENV = "ALERTPUSH_APP_SECRET"
FEISHU_ALARM_RECEIVE_ID_ENV = "FEISHU_ALARM_RECEIVE_ID"
FEISHU_ALARM_RECEIVE_ID_TYPE_ENV = "FEISHU_ALARM_RECEIVE_ID_TYPE"

__all__ = [
    "FEISHU_APP_ID_ENV",
    "FEISHU_APP_SECRET_ENV",
    "ALERTPUSH_APP_ID_ENV",
    "ALERTPUSH_APP_SECRET_ENV",
    "FEISHU_ALARM_RECEIVE_ID_ENV",
    "FEISHU_ALARM_RECEIVE_ID_TYPE_ENV",
]
